pipeline:
  name: ILOVE YOGA
  identifier: ILOVE_YOGA
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_2
                  identifier: Run_2
                  spec:
                    shell: Sh
                    command: echo "2"
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
